### ISSUE TITLE
Vendor packages

### ISSUE THREAD

**Issue by mrueg** [ovnworks/gobgp_exporter#1]
Would it be possible to vendor packages or provide a vendor lockfile?

**Comment by greenpau** [comment]
@mrueg , sure. Let me check.

**Comment by greenpau** [comment]
@mrueg , I looked and I did not have it. Over the weekend, I will and `dep` files. Do you care which `gobgp` version to use?

**Comment by mrueg** [comment]
Thanks a bunch! 
Since my personal use case is to use it in conjunction with https://github.com/cloudnativelabs/kube-router gobgp-1.33 would be perfect :)

**Comment by greenpau** [comment]
@mrueg , I started working on it. I want to make a few modification (structural) and add the authentication I implemented in [here](https://github.com/greenpau/network_exporter#security-first).

**Comment by greenpau** [comment]
@mrueg , this is now resolved. Please open an issue if the exporter does not produce the numbers you expect. Also, if you want to monitor something specific, I am happy adding it. 😄 

```
make dist
```

**Comment by mrueg** [comment]
Thanks a bunch! One further small suggestion, could you tag a release?

**Comment by greenpau** [comment]
> Thanks a bunch! One further small suggestion, could you tag a release?

@mrueg , done!
