### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mrueg** [ovnworks/gobgp_exporter#11]
Can you tag a new release for gobgp-2.x support?

**Comment by greenpau** [comment]
> Can you tag a new release for gobgp-2.x support?

@mrueg , yes, sure!

**Comment by greenpau** [comment]
@mrueg , done! https://github.com/forward53/gobgp_exporter/releases/tag/v1.1.2

**Comment by mrueg** [comment]
That was quick, thanks a lot!

**Comment by greenpau** [comment]
> That was quick, thanks a lot!

@mrueg , I developed [`versioned`](https://github.com/greenpau/versioned) utility. It makes it super quick :smile: Try it out!

https://github.com/forward53/gobgp_exporter/blob/23efdabea1d22af7c9ef2f570fd6c67a6eb8f069/Makefile#L96-L106
