### ISSUE TITLE
gobgp-exporter failed to init properly: context deadline exceeded  source="main.go:73" - help needed

### ISSUE THREAD

**Issue by learningChinmaya** [ovnworks/gobgp_exporter#16]
HI there,

I have followed the document to install the gobgp exporter locally. everything went well until execution of  $make. 
However $make qtest fails with following error..
$make qtest 
INFO[0000] Starting gobgp-exporter (version=1.1.3, branch=master, revision=v1.1.3-1-g1eeeea6)  source="main.go:68"
INFO[0000] Build context (go=go1.16.5, user=chimaya.dash, date=2021-07-14)  source="main.go:69"
ERRO[0002] gobgp-exporter failed to init properly: context deadline exceeded  source="main.go:73"

moreover when i manually run gobgp-exporter command, it works for --help, -metrics, -version flags and it fails for others flags.

Please assist. Thank you!

**Comment by greenpau** [comment]
@learningChinmaya , the exporter cannot connect to GoBGP instance.

https://github.com/greenpau/gobgp_exporter/blob/1eeeea6813fadcdc6151d0cfb920d7ea048e9a29/cmd/gobgp_exporter/main.go#L71-L75

**Comment by learningChinmaya** [comment]
Thank you @greenpau .
