### ISSUE TITLE
IPV6 compatibility for gobgp exporter

### ISSUE THREAD

**Issue by learningChinmaya** [ovnworks/gobgp_exporter#17]
Hi,

I have noticed that GOBGP exporter is not compatible with IPV6 address. It gives parsing error when I use IPV6 address to connect to remote server.

while scanning  we found, the below piece of code is throwing the error after validating the format.

**arr := strings.Split(s, ":")
	if len(arr) != 2 {
		return fmt.Errorf("invalid address %s, expected 'ipaddress:port'", s)**

 Will it be possible  to make it work for both IPV4 and IPV6? Please confirm.

Thank you!

**Comment by greenpau** [comment]
@learningChinmaya , will add a for it.

**Comment by learningChinmaya** [comment]
@greenpau Thank you! Would really appreciate your help on this regard. Please let me know once done.

**Comment by learningChinmaya** [comment]
@greenpau, I have also noticed that it doesn't work with FQDN. Is there any specific reason for being too restrictive or it can be modifies as well?

Please confirm. Thank you!

**Comment by learningChinmaya** [comment]
@greenpau, is it possible for you to provide a tentative date on when the fix will be applied? Please confirm.

Thank you!

**Comment by greenpau** [comment]
> is it possible for you to provide a tentative date on when the fix will be applied? Please confirm.

@learningChinmaya , not really. It is best effort at the moment. You could do a PR for it too.

**Comment by learningChinmaya** [comment]
@greenpau @sebastien-coavoux Thank you!

**Comment by greenpau** [comment]
@learningChinmaya , @sebastien-coavoux , will release shortly.

**Comment by greenpau** [comment]
Released v1.1.4

**Comment by learningChinmaya** [comment]
@greenpau Thank you!
