### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by akaczm** [ovnworks/gobgp_exporter#6]
`pkg/gobgp_exporter/collect.go:45:14: undefined: gobgpapi.GetServerRequest
pkg/gobgp_exporter/collect.go:46:32: n.client.Gobgp.GetServer undefined (type gobgpapi.GobgpApiClient has no field or method GetServer)
pkg/gobgp_exporter/collect_peers.go:28:21: undefined: gobgpapi.GetNeighborRequest
pkg/gobgp_exporter/collect_peers.go:31:37: n.client.Gobgp.GetNeighbor undefined (type gobgpapi.GobgpApiClient has no field or method GetNeighbor)`

Using CentOS 7
go1.13.8

I haven't much experience with building Go applications so the fault might be on me. Earlier I've been getting errors regarding vendor/github.com/osrg/gobgp/api/gobgp.pb.extended.go being nonexistant, so I cloned the gobgp repository in the above directory and the build commenced, until it ran into the aforementioned issue.

**Comment by greenpau** [comment]
@akaczm , the issue here is that the `gobgp` package is being compiled without https://github.com/ovnworks/gobgp_exporter/blob/master/assets/gobgp/gobgp.pb.extended.patch.go

In `go1.13.8`, there is a concept of modules. By default, it will disregards things in your `$GOPATH/src`.

> been getting errors regarding vendor/github.com/osrg/gobgp/api/gobgp.pb.extended.go being nonexistant, so I cloned the gobgp repository in the above directory and the build commenced, until it ran into the aforementioned issue.

First, clone the exporter to `${GOPATH}/src/github.com/ovnworks/gobgp_exporter`.

Next, clone the `gobgp` to `${GOPATH}/src/github.com/osrg/gobgp`.

In `gobgp_exporter`, create `go.mod`, then provide a replacement for where to get the library with the `replace` clause. For example, please see how I am using local `github.com/crewjam/saml` in https://github.com/greenpau/gatekeeper/blob/master/go.mod#L1-L16

Please don't hesitate asking questions! In fact, thank you for asking this one! ;-)

**Comment by greenpau** [comment]
@akaczm , I switched from  Gopkg to go modules [here](https://github.com/ovnworks/gobgp_exporter/commit/98b00c86c99aac10861d53923dd6aa25755a1378). I also noticed that I have other build errors:

```
$ make
Version: 1.1.1, Branch: master, Revision: v1.1.0-2-ga25c8c6-dirty
Build on 2020-02-25 by greenpau
GOPATH: /home/greenpau/dev/go
github.com/osrg/gobgp/api
github.com/ovnworks/gobgp_exporter/pkg/gobgp_exporter
# github.com/ovnworks/gobgp_exporter/pkg/gobgp_exporter
pkg/gobgp_exporter/collect.go:45:14: undefined: gobgpapi.GetServerRequest
pkg/gobgp_exporter/collect.go:46:32: n.client.Gobgp.GetServer undefined (type gobgpapi.GobgpApiClient has no field or method GetServer)
pkg/gobgp_exporter/collect_peers.go:28:21: undefined: gobgpapi.GetNeighborRequest
pkg/gobgp_exporter/collect_peers.go:31:37: n.client.Gobgp.GetNeighbor undefined (type gobgpapi.GobgpApiClient has no field or method GetNeighbor)
pkg/gobgp_exporter/collect_rib.go:30:35: undefined: gobgpapi.Resource_name
pkg/gobgp_exporter/collect_rib.go:31:37: undefined: gobgpapi.Family_name
pkg/gobgp_exporter/collect_rib.go:41:21: undefined: gobgpapi.Resource
pkg/gobgp_exporter/collect_rib.go:44:20: undefined: gobgpapi.Resource_GLOBAL
pkg/gobgp_exporter/collect_rib.go:46:20: undefined: gobgpapi.Resource_LOCAL
```

It looks like the API have changed. Will take a look at it shortly.

**Comment by greenpau** [comment]
@akaczm , I also amended build instructions [here](https://github.com/ovnworks/gobgp_exporter/commit/8e39d9c8761df34eb784a7fc2ebafcf793cc044a).

**Comment by greenpau** [comment]
@akaczm , since I worked on `gobgp`, the authors significantly changed GoBGP API! 

For example, `GetNeighbor` is no longer there. However, this quick search yields:

```
../../osrg/gobgp/api/gobgp.pb.go:func (m *Path) GetNeighborIp() string {
../../osrg/gobgp/api/gobgp.pb.go:func (m *PeerConf) GetNeighborAddress() string {
../../osrg/gobgp/api/gobgp.pb.go:func (m *PeerConf) GetNeighborInterface() string {
../../osrg/gobgp/api/gobgp.pb.go:func (m *PeerState) GetNeighborAddress() string {
../../osrg/gobgp/api/gobgp.pb.go:func (m *Conditions) GetNeighborSet() *MatchSet {
```

In sum, I will try bringing this exporter into shape.

**Comment by akaczm** [comment]
Thank you for the prompt and in depth investigation of this issue! I wish I could be of assistance in fixing the exporter.

**Comment by greenpau** [comment]
> Thank you for the prompt and in depth investigation of this issue! I wish I could be of assistance in fixing the exporter.

@akaczm , 👍

**Comment by greenpau** [comment]
@akaczm , it is all fixed now. No need to do `replace` in `go.mod`. The client API now supports most of the calls.

**Comment by greenpau** [comment]
@akaczm , please try rebuild once again.

**Comment by akaczm** [comment]
@greenpau it appears the program now builds and runs properly and is scraping gobgp metrics properly as well
Thank you for the very fast reaction time on resolving this issue!
`
gobgp-exporter 1.1.1, commit: v1.1.0-7-g38ebe31
INFO[0000] Starting gobgp-exporter (version=1.1.1, branch=master, revision=v1.1.0-7-g38ebe31)  source="main.go:68"
INFO[0000] Build context (go=go1.13.8, user=XXX, date=2020-02-27)  source="main.go:69"
DEBU[0000] NewExporter() initialized successfully        source="gobgp_exporter.go:76"
INFO[0000] Minimal scrape interval: 5 seconds            source="main.go:83"
INFO[0000] Listening on 0.0.0.0:9474                     source="main.go:93"
`
